table factor_volatility
	lineageTag: 1a7514ff-bef8-4911-8839-0abf27303054

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 284130e2-abfb-4eda-9141-ea7c84de1503
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column pct_change
		dataType: double
		lineageTag: 4b9398ca-cc75-45f9-b811-e23a18174555
		summarizeBy: sum
		sourceColumn: pct_change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_volatility
		dataType: double
		lineageTag: 160be06b-daa8-4285-81d7-f10dea68b23e
		summarizeBy: sum
		sourceColumn: rolling_volatility

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition factor_volatility = m
		mode: import
		source =
				let
				    Source = Sql.Database("fhi24zxnvquurfybnnzrkz22aq-ae4c5pcutjkedh2gfko4iqwk24.datawarehouse.fabric.microsoft.com", "analytics_warehouse"),
				    dbo_factor_volatility = Source{[Schema="dbo",Item="factor_volatility"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_factor_volatility,{{"Date", type date}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"Date", type text}}, "en-US"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"Date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

