table forecast_accuracy
	lineageTag: c247b326-93c8-470a-bf56-06a81d7a6cc1

	/// 1 - (model error / naive error) over the trailing 26 weeks. Above zero means the model beat "the price won't move". Null until 26 weeks of outcomes exist, and blank is honest here - do not coalesce it to zero.
	///
	/// Shown as a percentage: a skill score is conventionally quoted either way, and "16.3% less error than assuming no change" needs no explaining where "0.163" does. The negative tail reads correctly too - -98% is 98% MORE error than the benchmark - but it is unbounded below, so a very bad window can print a number past -100%.
	measure Skill = AVERAGE(forecast_accuracy[skill_26w])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1e392f06-e54b-473a-a4f3-bab27292791d

	/// Mean absolute error of the model over the trailing 26 weeks, in c/L.
	measure 'Model MAE 26w' = AVERAGE(forecast_accuracy[mae_model_26w])
		formatString: 0.00
		lineageTag: e7da4bc0-d992-4e0a-8bd7-b6cb6b74ce59

	/// Same window, for the "price won't change" benchmark. The pair is the point: in volatile weeks both roughly double.
	measure 'Naive MAE 26w' = AVERAGE(forecast_accuracy[mae_naive_26w])
		formatString: 0.00
		lineageTag: 2bbfbe3f-485a-430e-9b54-f0859de1bf83

	/// Share of weeks where the model led naive. Denominator counts only weeks with a full window, so early history is excluded rather than scored as a loss.
	measure 'Weeks Model Ahead %' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(forecast_accuracy),
			        forecast_accuracy[skill_26w] > 0
			    ),
			    CALCULATE(
			        COUNTROWS(forecast_accuracy),
			        NOT ISBLANK(forecast_accuracy[skill_26w])
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6e3298d8-64e7-4624-b1f7-9d5c11df01fe

	/// Signed: positive means the model would have called the week high. Guarded, because a plain subtraction reads a missing outcome as zero and would draw the three pending weeks as a ~250 c/L error.
	measure 'Forecast Error' =
			
			VAR Actual = SUM(forecast_accuracy[actual_price])
			VAR Called = SUM(forecast_accuracy[pred_adl_ecm])
			RETURN
			IF(NOT ISBLANK(Actual), Called - Actual)
		formatString: 0.00
		lineageTag: b28070c8-b777-4dd7-9a73-0f1f6da40e0f

	/// What the pump price actually was at the target week. Blank for the three weeks that have not arrived.
	measure 'Actual Price' = AVERAGE(forecast_accuracy[actual_price])
		formatString: 0.0
		lineageTag: 29d45101-b648-4d68-833d-73b06af1b44b

	/// What the model would have indicated for that week, refitting on data available then. AVERAGE not SUM: with one fuel and one horizon selected there is exactly one row per week, and AVERAGE degrades gracefully if a slicer is widened instead of silently adding two fuels together.
	measure 'Model Call' = AVERAGE(forecast_accuracy[pred_adl_ecm])
		formatString: 0.0
		lineageTag: 6dfcf04a-7812-474f-8407-46e3d82e83b1

	/// The benchmark: "the price won't change".
	measure 'Naive Call' = AVERAGE(forecast_accuracy[pred_naive])
		formatString: 0.0
		lineageTag: cdf98303-a7bc-473c-9b35-6efc9f66cefa

	/// Column fill for the error chart. Red where the model would have called the week high, blue where low - the same blue the model's line carries above.
	measure 'Error Colour' =

			IF(ISBLANK([Forecast Error]), BLANK(), IF([Forecast Error] >= 0, "#ef4444", "#0ea5e9"))
		lineageTag: d60649f7-0257-4d92-bfb6-8c7205002324

	/// Zero on every week that carries a call, blank never - and that is the whole job.
	///
	/// The three charts share one axis field but not one axis RANGE: the price chart
	/// runs to the last call (28 Aug), while error and skill stop at the last week
	/// whose outcome exists. Power BI sizes each axis to the data it has, so on a
	/// short window the lower charts were drawn narrower and their columns no longer
	/// sat under the weeks they belong to. Adding this as a second series extends
	/// their domain to match without inventing an error or a skill value: a column of
	/// height zero draws nothing.
	measure 'Axis Anchor' =

			IF(NOT ISBLANK([Model Call]), 0)
		formatString: 0
		lineageTag: 273bafc6-941f-43ee-adef-1e3ba79a7c7b

	/// Pump-nozzle colours, carried over from the old Report 1 so the buttons look the way readers already know: green for 91, yellow for 95, grey for diesel.
	measure 'Fuel Colour' =

			SWITCH(
			    SELECTEDVALUE(forecast_accuracy[fuel]),
			    "Regular Petrol", "#40B54A",
			    "Premium Petrol 95R", "#F7EC14",
			    "Diesel", "#cccccc",
			    "#6b7280"
			)
		lineageTag: 8c698132-7689-4030-b58e-f9d67520d2b4

	/// Split in two so the area above zero can be blue and the area below red. Power BI cannot fill one series by sign, and two series that never overlap read as one shape.
	measure 'Skill Above Zero' =
			
			VAR s = [Skill]
			RETURN
			IF(s > 0, s)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 157f54a3-eced-4a3c-9f0e-6f00a25b6707

	measure 'Skill Below Zero' =
			
			VAR s = [Skill]
			RETURN
			IF(s < 0, s)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 82906c20-64a7-4336-bf9d-b53139d4ec05

	/// Drives the strip under the price chart. Marks a week that is either volatile or not yet finalised - the two things a reader has to know before trusting a point. Keyed on the week the call was made.
	measure 'Timeline Band' =
			
			VAR VolRegime = SELECTEDVALUE(forecast_accuracy[crude_vol_regime])
			VAR InputState = SELECTEDVALUE(forecast_accuracy[input_status])
			RETURN
			IF(VolRegime = "high" || InputState = "provisional", 1)
		formatString: 0
		lineageTag: d6b05b87-d5c8-4a8c-9019-7e9ba61b11d2

	/// Amber for volatile, grey for provisional inputs. Where a week is both, volatility wins: it is the louder fact, and the tooltip still names the status.
	measure 'Timeline Band Colour' =
			
			IF(SELECTEDVALUE(forecast_accuracy[crude_vol_regime]) = "high", "#f59e0b", "#9ca3af")
		lineageTag: 381e7fdf-bc39-4a4c-a476-2f11e9189ca0

	/// The price chart's heading. Written as a measure because the horizon is a slicer choice, and a fixed heading would let two series of different informedness look comparable.
	measure 'Price Chart Title' =
			
			VAR H = SELECTEDVALUE(forecast_accuracy[horizon_weeks])
			RETURN
			"What the model would have indicated, against what happened (c/L). "
			    & "Every point was called "
			    & H
			    & IF(H = 1, " week", " weeks")
			    & " before the date beneath it"
		lineageTag: 757dde39-ad16-4096-ba99-7272636f0ef4

	/// Status of the week's inputs, for the strip's tooltip.
	measure 'Input Status' = SELECTEDVALUE(forecast_accuracy[input_status])
		lineageTag: 76a7ebdc-1bfe-465e-8f5e-33c736c906f4

	/// Named episode behind a volatile stretch, for the strip's tooltip.
	measure Episode = SELECTEDVALUE(forecast_accuracy[crude_episode_id])
		lineageTag: 1d25dfa1-1e4e-4049-8168-d459ff54fdfd

	column week_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb85dbcf-9b9b-4044-a848-006fdc1c6a3e
		summarizeBy: none
		sourceColumn: week_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Target week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a0e94f81-29ad-46a0-b5e4-2dcd186e5f60
		summarizeBy: none
		sourceColumn: Target week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fuel
		dataType: string
		lineageTag: 1b9719ca-85c4-4771-bad6-aaefe821190c
		summarizeBy: none
		sourceColumn: fuel

		annotation SummarizationSetBy = Automatic

	column horizon_weeks
		dataType: int64
		formatString: 0
		lineageTag: 04f801a8-a874-4c5b-8b20-c52c247140b3
		summarizeBy: sum
		sourceColumn: horizon_weeks

		annotation SummarizationSetBy = Automatic

	column input_status
		dataType: string
		lineageTag: 7911a957-ad1d-4a94-bc88-7804ae27afdf
		summarizeBy: none
		sourceColumn: input_status

		annotation SummarizationSetBy = Automatic

	column outcome_known
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ac413b9d-240e-4b9d-96ce-15952f1a322f
		summarizeBy: none
		sourceColumn: outcome_known

		annotation SummarizationSetBy = Automatic

	column price_now
		dataType: double
		lineageTag: af8c2442-62c8-4784-854e-b3505210f1f5
		summarizeBy: sum
		sourceColumn: price_now

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column actual_price
		dataType: double
		lineageTag: 7b8d1309-cef8-4aae-8435-6f8b01c79586
		summarizeBy: sum
		sourceColumn: actual_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pred_adl
		dataType: double
		lineageTag: a111b5a0-7327-45ff-b3f9-5e7aecc7b445
		summarizeBy: sum
		sourceColumn: pred_adl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pred_adl_ecm
		dataType: double
		lineageTag: 4d26b2d0-3e35-4089-a229-e806dfc4f843
		summarizeBy: sum
		sourceColumn: pred_adl_ecm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pred_naive
		dataType: double
		lineageTag: c7e6818a-1273-4640-a03c-a8fd78630f5e
		summarizeBy: sum
		sourceColumn: pred_naive

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pred_report1_ish
		dataType: double
		lineageTag: 6eb4a518-fd57-4e82-8b89-b8f5f3251659
		summarizeBy: sum
		sourceColumn: pred_report1_ish

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abs_err_adl
		dataType: double
		lineageTag: 4e724007-58e9-4e55-993a-d165618088a3
		summarizeBy: sum
		sourceColumn: abs_err_adl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abs_err_adl_ecm
		dataType: double
		lineageTag: 4f074f15-e24e-41e0-b2b9-14d3776b2341
		summarizeBy: sum
		sourceColumn: abs_err_adl_ecm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abs_err_naive
		dataType: double
		lineageTag: 3e764bbf-b77f-41aa-b67f-be011c630127
		summarizeBy: sum
		sourceColumn: abs_err_naive

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abs_err_report1
		dataType: double
		lineageTag: 622e5355-489c-4e4c-9c91-5cdba0370cc7
		summarizeBy: sum
		sourceColumn: abs_err_report1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mae_model_26w
		dataType: double
		lineageTag: e35198a7-6747-4b8f-914c-df654e9cea85
		summarizeBy: sum
		sourceColumn: mae_model_26w

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mae_naive_26w
		dataType: double
		lineageTag: b0dfb186-93ba-4318-b782-c4de0e3b75a3
		summarizeBy: sum
		sourceColumn: mae_naive_26w

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mae_report1_26w
		dataType: double
		lineageTag: bf0b6f62-8214-429b-b795-40802c336493
		summarizeBy: sum
		sourceColumn: mae_report1_26w

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column window_n
		dataType: int64
		formatString: 0
		lineageTag: 4fe3e6ef-72db-4207-8a0b-913f638ffff9
		summarizeBy: sum
		sourceColumn: window_n

		annotation SummarizationSetBy = Automatic

	column skill_26w
		dataType: double
		lineageTag: 7bde66e0-a9ff-4c58-87bc-d9fd776cfe0f
		summarizeBy: sum
		sourceColumn: skill_26w

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column skill_report1_26w
		dataType: double
		lineageTag: 7b970b42-afb3-49a4-8189-a01dc52f61e9
		summarizeBy: sum
		sourceColumn: skill_report1_26w

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crude_vol_regime
		dataType: string
		lineageTag: 04f28203-bad9-433b-9588-6ecdba1a6b87
		summarizeBy: none
		sourceColumn: crude_vol_regime

		annotation SummarizationSetBy = Automatic

	column crude_episode_id
		dataType: string
		lineageTag: 9c0298fe-8412-4d84-883b-860099685cc0
		summarizeBy: none
		sourceColumn: crude_episode_id

		annotation SummarizationSetBy = Automatic

	column crude_move_regime
		dataType: string
		lineageTag: 2ca90a00-f907-4122-bd40-5a8d22933050
		summarizeBy: none
		sourceColumn: crude_move_regime

		annotation SummarizationSetBy = Automatic

	column flag_data_status
		dataType: string
		lineageTag: 666114ca-cfcf-4855-bad6-849721041ecc
		summarizeBy: none
		sourceColumn: flag_data_status

		annotation SummarizationSetBy = Automatic

	partition forecast_accuracy = m
		mode: import
		source =
				let
				    Source = Sql.Database("fhi24zxnvquurfybnnzrkz22aq-ae4c5pcutjkedh2gfko4iqwk24.datawarehouse.fabric.microsoft.com", "analytics_warehouse"),
				    dbo_forecast_accuracy = Source{[Schema="dbo",Item="forecast_accuracy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_forecast_accuracy,{{"target_week", "Target week"}})
				in
				    #"Renamed Columns"

